In [57]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [58]:
np.ones(3)

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [59]:
np.zeros(3)

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [60]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
x+y

array([ 6,  8, 10, 12])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [61]:
print('Dimension:',x.ndim)
print('shape:',x.shape)
print('size:',x.size)
print('type:',x.dtype)

Dimension: 1
shape: (4,)
size: 4
type: int64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [62]:
# write your code here ^_^
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [63]:
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [64]:
z=z.reshape(-1,1)
newArray=np.hstack([z,w])
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [65]:
for row in newArray:
  for element in row:
    print(element,end=' ')

1 11 12 2 13 14 3 15 16 

## Q#9: Reverse the columns and rows of "newArray".

In [66]:
newArray=newArray[::-1,::-1]
newArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [67]:
newArray=newArray -1
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

## Q#11: Find smallest and biggest values in "newArray".

In [68]:
print('Max:',newArray.max())
print('Min:',newArray.min())

Max: 15
Min: 0


## Q#12: Print the first row of "newArray" using indexing.

In [69]:
newArray[0,:]

array([15, 14,  2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [70]:
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [71]:
print(newArray[2,-1])
print(newArray[1,0])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [72]:
# write your code here ^_^
newArray=newArray.reshape(9,1)
newArray

array([[15],
       [14],
       [ 2],
       [13],
       [12],
       [ 1],
       [11],
       [10],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

In [73]:
# i have removed last 3 element in newArray to be able to fit shape(3,2)
newArray=newArray[:-3].reshape(3,2)
newArray

array([[15, 14],
       [ 2, 13],
       [12,  1]])

# Well Done 🎉